<div id="buckaroo_magento2_payconiq_loader" class="loading-mask"></div>

<div id="buckaroo_magento2_payconiq_container">
    <div id="buckaroo_magento2_mrcash_items">
        <p id="buckaroo_magento2_mrcash_title"><?= /* @noEscape */ __('Scan onderstaande code binnen 15 minuten met de'); ?>&nbsp;
            <a target="_blank" href="https://www.bancontact.com/nl"><?= /* @noEscape */ __('Bancontact app'); ?></a></p>
        <div id="buckaroo_magento2_mrcash_qr"></div>
        <button id="buckaroo_magento2_mrcash_url" type="button" style="display: none;"></button>

        <button id="buckaroo_magento2_mrcash_cancel" type="button" title="Cancel" data-bind="click: cancelPayment">
            <span><?= /* @noEscape */ (__('Cancel')); ?></span>
        </button>
    </div>
</div>

<script>
    require(['buckaroo/mrcash/pay'], function (mrcashPay) {
        var transactionKey = "<?= /* @noEscape */ ($block->getTransactionKey()); ?>";

        mrcashPay.setTransactionKey(transactionKey);
        mrcashPay.showQrCode();
    });
    cancelPayment = function() {
        require(['buckaroo/mrcash/pay'], function (mrcashPay) {
            mrcashPay.cancelPayment();
        });
    }
</script>
