<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile
$post = $block->getRequest()->getPost('creditmemo');
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if (isset($_total['block_name']) && $_total['block_name'] == 'buckaroo_already_paid'): ?>
        <tr>
            <td class="label"><?php echo $block->escapeHtml($_total['label']) ?><div id="buckaroo_already_paid_adv"></div></td>
            <td>
                <input type="text"
                       name="creditmemo[buckaroo_already_paid][<?php echo $block->escapeHtmlAttr($_total['transaction_id']) ?>]"
                       value="<?php echo $block->escapeHtmlAttr(abs(isset($post['buckaroo_already_paid'][$_total['transaction_id']])?$post['buckaroo_already_paid'][$_total['transaction_id']]:$_total['value'])) ?>"
                       class="input-text admin__control-text not-negative-amount"
                       id="buckaroo_already_paid" />
            </td>
        </tr>
    <?php endif?>
<?php endforeach?>
