<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile

?>

<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if (isset($_total['block_name']) && $_total['block_name'] == 'buckaroo_fee_afterpay'): ?>
        <tr>
            <td class="label"><?php echo $block->escapeHtml($_total['label']) ?>
                <input type="checkbox" name="creditmemo[buckaroo_fee_refundable]" id="isRefund" checked>
                <div id="buckaroo_fee_adv">
                </div>
            </td>
            <td>
                <span class="price"><?php echo $block->getCurrentCurrencySymbol() . abs($_total['value']) ?></span>
            </td>
        </tr>
    <?php endif?>
<?php endforeach?>
