<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * It is available through the world-wide-web at this URL:
 * https://tldrlegal.com/license/mit-license
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to support@buckaroo.nl so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for your
 * needs please contact support@buckaroo.nl for more information.
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   https://tldrlegal.com/license/mit-license
 */

namespace Buckaroo\Magento2\Model;

class PaypalStateCodes
{
    /**
     * Contains all state codes and the relevant full names for the countries paypal supports (or requires) state codes
     * for.
     *
     * @var array
     */
    private $_codes = [
        'CA' => [
            'AB' => ['Alberta'],
            'BC' => ['British Columbia'],
            'MB' => ['Manitoba'],
            'NB' => ['New Brunswick'],
            'NL' => ['Newfoundland and Labrador', 'Newfoundland', 'Labrador'],
            'NT' => ['Northwest Territories'],
            'NS' => ['Nova Scotia'],
            'NU' => ['Nunavut'],
            'ON' => ['Ontario'],
            'PE' => ['Prince Edward Island'],
            'QC' => ['Quebec'],
            'SK' => ['Saskatchewan'],
            'YT' => ['Yukon Territory', 'Yukon'],
        ],
        'IT' => [
            'AG' => ['Agrigento'],
            'AL' => ['Alessandria'],
            'AN' => ['Ancona'],
            'AO' => ['Aosta'],
            'AR' => ['Arezzo'],
            'AP' => ['Ascoli Piceno'],
            'AT' => ['Asti'],
            'AV' => ['Avellino'],
            'BA' => ['Bari'],
            'BL' => ['Belluno'],
            'BN' => ['Benevento'],
            'BG' => ['Bergamo'],
            'BI' => ['Biella'],
            'BO' => ['Bologna'],
            'BZ' => ['Bolzano'],
            'BS' => ['Brescia'],
            'BR' => ['Brindisi'],
            'CA' => ['Cagliari'],
            'CL' => ['Caltanissetta'],
            'CB' => ['Campobasso'],
            'CE' => ['Caserta'],
            'CT' => ['Catania'],
            'CZ' => ['Catanzaro'],
            'CH' => ['Chieti'],
            'CO' => ['Como'],
            'CS' => ['Cosenza'],
            'CR' => ['Cremona'],
            'KR' => ['Crotone'],
            'CN' => ['Cuneo'],
            'EN' => ['Enna'],
            'FE' => ['Ferrarav'],
            'FI' => ['Firenze'],
            'FG' => ['Foggia'],
            'FO' => ['Forli-Cesena'],
            'FR' => ['Frosinone'],
            'GE' => ['Genova'],
            'GO' => ['Gorizia'],
            'GR' => ['Grosseto'],
            'IM' => ['Imperia'],
            'IS' => ['Isernia'],
            'SP' => ['La Spezia'],
            'AQ' => ['L’Aquila'],
            'LT' => ['Latina'],
            'LE' => ['Lecce'],
            'LC' => ['Lecco'],
            'LI' => ['Livorno'],
            'LO' => ['Lodi'],
            'LU' => ['Lucca'],
            'MC' => ['Macerata'],
            'MN' => ['Mantova'],
            'MS' => ['Massa-Carrara'],
            'MT' => ['Matera'],
            'ME' => ['Messina'],
            'MI' => ['Milano'],
            'MO' => ['Modena'],
            'MB' => ['Monza e Brianza'],
            'NA' => ['Napoli'],
            'NO' => ['Novara'],
            'NU' => ['Nuoro'],
            'OR' => ['Oristano'],
            'PD' => ['Padova'],
            'PA' => ['Palermo'],
            'PR' => ['Parma'],
            'PV' => ['Pavia'],
            'PG' => ['Perugia'],
            'PS' => ['Pesaro'],
            'PE' => ['Pescara'],
            'PC' => ['Piacenza'],
            'PI' => ['Pisa'],
            'PT' => ['Pistoia'],
            'PN' => ['Pordenone'],
            'PZ' => ['Potenza'],
            'PO' => ['Prato'],
            'RG' => ['Ragusa'],
            'RA' => ['Ravenna'],
            'RC' => ['Reggio Calabria'],
            'RE' => ['Reggio Emilia'],
            'RI' => ['Rieti'],
            'RN' => ['Rimini'],
            'RM' => ['Roma'],
            'RO' => ['Rovigo'],
            'SA' => ['Salerno'],
            'SS' => ['Sassari'],
            'SV' => ['Savona'],
            'SI' => ['Siena'],
            'SR' => ['Siracusa'],
            'SO' => ['Sondrio'],
            'TA' => ['Taranto'],
            'TE' => ['Teramo'],
            'TR' => ['Terni'],
            'TO' => ['Torino'],
            'TP' => ['Trapani'],
            'TN' => ['Trento'],
            'TV' => ['Treviso'],
            'TS' => ['Trieste'],
            'UD' => ['Udine'],
            'VA' => ['Varese'],
            'VE' => ['Venezia'],
            'VB' => ['Verbania-Cusio-Ossola'],
            'VC' => ['Vercelli'],
            'VR' => ['Verona'],
            'VV' => ['Vibo Valentia'],
            'VI' => ['Vicenza'],
            'VT' => ['Viterbo'],
        ],
        'NL' => [
            'DR' => ['Drenthe'],
            'FL' => ['Flevoland'],
            'FR' => ['Friesland'],
            'GE' => ['Gelderland'],
            'GR' => ['Groningen'],
            'LI' => ['Limburg'],
            'NB' => ['Noord-Brabant'],
            'NH' => ['Noord-Holland'],
            'OV' => ['Overijssel'],
            'UT' => ['Utrecht'],
            'ZE' => ['Zeeland'],
            'ZH' => ['Zuid-Holland'],
        ],
        'AR' => [
            'CIUDAD AUTÓNOMA DE BUENOS AIRES' => ['Buenos Aires (Ciudad)'],
            'BUENOS AIRES' => ['Buenos Aires (Provincia)'],
            'CATAMARCA' => ['Catamarca'],
            'CHACO' => ['Chaco'],
            'CHUBUT' => ['Chubut'],
            'CORRIENTES' => ['Corrientes'],
            'CÓRDOBA' => ['Córdoba'],
            'ENTRE RÍOS' => ['Entre Ríos'],
            'FORMOSA' => ['Formosa'],
            'JUJUY' => ['Jujuy'],
            'LA PAMPA' => ['La Pampa'],
            'LA RIOJA' => ['La Rioja'],
            'MENDOZA' => ['Mendoza'],
            'MISIONES' => ['Misiones'],
            'NEUQUÉN' => ['Neuquén'],
            'RÍO NEGRO' => ['Río Negro'],
            'SALTA' => ['Salta'],
            'SAN JUAN' => ['San Juan'],
            'SAN LUIS' => ['San Luis'],
            'SANTA CRUZ' => ['Santa Cruz'],
            'SANTA FE' => ['Santa Fe'],
            'SANTIAGO DEL ESTERO' => ['Santiago del Estero'],
            'TIERRA DEL FUEGO' => ['Tierra del Fuego'],
            'TUCUMÁN' => ['Tucumán'],
        ],
        'BR' => [
            'AC' => ['Acre'],
            'AL' => ['Alagoas'],
            'AP' => ['Amapá'],
            'AM' => ['Amazonas'],
            'BA' => ['Bahia'],
            'CE' => ['Ceará'],
            'DF' => ['Distrito Federal'],
            'ES' => ['Espírito Santo'],
            'GO' => ['Goiás'],
            'MA' => ['Maranhão'],
            'MT' => ['Mato Grosso'],
            'MS' => ['Mato Grosso do Sul'],
            'MG' => ['Minas Gerais'],
            'PR' => ['Paraná'],
            'PB' => ['Paraíba'],
            'PA' => ['Pará'],
            'PE' => ['Pernambuco'],
            'PI' => ['Piauí'],
            'RN' => ['Rio Grande do Norte'],
            'RS' => ['Rio Grande do Sul'],
            'RJ' => ['Rio de Janeiro'],
            'RO' => ['Rondônia'],
            'RR' => ['Roraima'],
            'SC' => ['Santa Catarina'],
            'SE' => ['Sergipe'],
            'SP' => ['São Paulo'],
            'TO' => ['Tocantins'],
        ],
        'IN' => [
            'Andaman and Nicobar Islands' => ['Andaman and Nicobar Islands'],
            'Andhra Pradesh' => ['Andhra Pradesh'],
            'APO' => ['Army Post Office'],
            'Arunachal Pradesh' => ['Arunachal Pradesh'],
            'Assam' => ['Assam'],
            'Bihar' => ['Bihar'],
            'Chandigarh' => ['Chandigarh'],
            'Chhattisgarh' => ['Chhattisgarh'],
            'Dadra and Nagar Haveli' => ['Dadra and Nagar Haveli'],
            'Daman and Diu' => ['Daman and Diu'],
            'Delhi (NCT)' => ['Delhi'],
            'Goa' => ['Goa'],
            'Gujarat' => ['Gujarat'],
            'Haryana' => ['Haryana'],
            'Himachal Pradesh' => ['Himachal Pradesh'],
            'Jammu and Kashmir' => ['Jammu and Kashmir'],
            'Jharkhand' => ['Jharkhand'],
            'Karnataka' => ['Karnataka'],
            'Kerala' => ['Kerala'],
            'Lakshadweep' => ['Lakshadweep'],
            'Madhya Pradesh' => ['Madhya Pradesh'],
            'Maharashtra' => ['Maharashtra'],
            'Manipur' => ['Manipur'],
            'Meghalaya' => ['Meghalaya'],
            'Mizoram' => ['Mizoram'],
            'Nagaland' => ['Nagaland'],
            'Odisha' => ['Odisha'],
            'Puducherry' => ['Puducherry'],
            'Punjab' => ['Punjab'],
            'Rajasthan' => ['Rajasthan'],
            'Sikkim' => ['Sikkim'],
            'Tamil Nadu' => ['Tamil Nadu'],
            'Telangana' => ['Telangana'],
            'Tripura' => ['Tripura'],
            'Uttar Pradesh' => ['Uttar Pradesh'],
            'Uttarakhand' => ['Uttarakhand'],
            'West Bengal' => ['West Bengal'],
        ],
        'ID' => [
            'ID-BA' => ['Bali'],
            'ID-BB' => ['Bangka Belitung'],
            'ID-BT' => ['Banten'],
            'ID-BE' => ['Bengkulu'],
            'ID-YO' => ['DI Yogyakarta'],
            'ID-JK' => ['DKI Jakarta'],
            'ID-GO' => ['Gorontalo'],
            'ID-JA' => ['Jambi'],
            'ID-JB' => ['Jawa Barat'],
            'ID-JT' => ['Jawa Tengah'],
            'ID-JI' => ['Jawa Timur'],
            'ID-KB' => ['Kalimantan Barat'],
            'ID-KS' => ['Kalimantan Selatan'],
            'ID-KT' => ['Kalimantan Tengah'],
            'ID-KI' => ['Kalimantan Timur'],
            'ID-KU' => ['Kalimantan Utara'],
            'ID-KR' => ['Kepulauan Riau'],
            'ID-LA' => ['Lampung'],
            'ID-MA' => ['Maluku'],
            'ID-MU' => ['Maluku Utara'],
            'ID-AC' => ['Nanggroe Aceh Darussalam'],
            'ID-NB' => ['Nusa Tenggara Barat'],
            'ID-NT' => ['Nusa Tenggara Timur'],
            'ID-PA' => ['Papua'],
            'ID-PB' => ['Papua Barat'],
            'ID-RI' => ['Riau'],
            'ID-SR' => ['Sulawesi Barat'],
            'ID-SN' => ['Sulawesi Selatan'],
            'ID-ST' => ['Sulawesi Tengah'],
            'ID-SG' => ['Sulawesi Tenggara'],
            'ID-SA' => ['Sulawesi Utara'],
            'ID-SB' => ['Sumatera Barat'],
            'ID-SS' => ['Sumatera Selatan'],
            'ID-SU' => ['Sumatera Utara'],
        ],
        'JP' => [
            'AICHI-KEN' => ['Aichi'],
            'AKITA-KEN' => ['Akita'],
            'AOMORI-KEN' => ['Aomori'],
            'CHIBA-KEN' => ['Chiba'],
            'EHIME-KEN' => ['Ehime'],
            'FUKUI-KEN' => ['Fukui'],
            'FUKUOKA-KEN' => ['Fukuoka'],
            'FUKUSHIMA-KEN' => ['Fukushima'],
            'GIFU-KEN' => ['Gifu'],
            'GUNMA-KEN' => ['Gunma'],
            'HIROSHIMA-KEN' => ['Hiroshima'],
            'HOKKAIDO' => ['Hokkaido'],
            'HYOGO-KEN' => ['Hyogo'],
            'IBARAKI-KEN' => ['Ibaraki'],
            'ISHIKAWA-KEN' => ['Ishikawa'],
            'IWATE-KEN' => ['Iwate'],
            'KAGAWA-KEN' => ['Kagawa'],
            'KAGOSHIMA-KEN' => ['Kagoshima'],
            'KANAGAWA-KEN' => ['Kanagawa'],
            'KOCHI-KEN' => ['Kochi'],
            'KUMAMOTO-KEN' => ['Kumamoto'],
            'KYOTO-FU' => ['Kyoto'],
            'MIE-KEN' => ['Mie'],
            'MIYAGI-KEN' => ['Miyagi'],
            'MIYAZAKI-KEN' => ['Miyazaki'],
            'NAGANO-KEN' => ['Nagano'],
            'NAGASAKI-KEN' => ['Nagasaki'],
            'NARA-KEN' => ['Nara'],
            'NIIGATA-KEN' => ['Niigata'],
            'OITA-KEN' => ['Oita'],
            'OKAYAMA-KEN' => ['Okayama'],
            'OKINAWA-KEN' => ['Okinawa'],
            'OSAKA-FU' => ['Osaka'],
            'SAGA-KEN' => ['Saga'],
            'SAITAMA-KEN' => ['Saitama'],
            'SHIGA-KEN' => ['Shiga'],
            'SHIMANE-KEN' => ['Shimane'],
            'SHIZUOKA-KEN' => ['Shizuoka'],
            'TOCHIGI-KEN' => ['Tochigi'],
            'TOKUSHIMA-KEN' => ['Tokushima'],
            'TOKYO-TO' => ['Tokyo'],
            'TOTTORI-KEN' => ['Tottori'],
            'TOYAMA-KEN' => ['Toyama'],
            'WAKAYAMA-KEN' => ['Wakayama'],
            'YAMAGATA-KEN' => ['Yamagata'],
            'YAMAGUCHI-KEN' => ['Yamaguchi'],
            'YAMANASHI-KEN' => ['Yamanashi'],
        ],
        'MX' => [
            'AGS' => ['Aguascalientes'],
            'BC' => ['Baja California'],
            'BCS' => ['Baja California Sur'],
            'CAMP' => ['Campeche'],
            'CHIS' => ['Chiapas'],
            'CHIH' => ['Chihuahua'],
            'CDMX' => ['Ciudad de México'],
            'COAH' => ['Coahuila'],
            'COL' => ['Colima'],
            'DF' => ['Distrito Federal'],
            'DGO' => ['Durango'],
            'MEX' => ['Estado de México'],
            'GTO' => ['Guanajuato'],
            'GRO' => ['Guerrero'],
            'HGO' => ['Hidalgo'],
            'JAL' => ['Jalisco'],
            'MICH' => ['Michoacán'],
            'MOR' => ['Morelos'],
            'NAY' => ['Nayarit'],
            'NL' => ['Nuevo León'],
            'OAX' => ['Oaxaca'],
            'PUE' => ['Puebla'],
            'QRO' => ['Querétaro'],
            'Q ROO' => ['Quintana Roo'],
            'SLP' => ['San Luis Potosí'],
            'SIN' => ['Sinaloa'],
            'SON' => ['Sonora'],
            'TAB' => ['Tabasco'],
            'TAMPS' => ['Tamaulipas'],
            'TLAX' => ['Tlaxcala'],
            'VER' => ['Veracruz'],
            'YUC' => ['Yucatán'],
            'ZAC' => ['Zacatecas'],
        ],
        'CN' => [
            'CN-AH' => ['Anhui Sheng'],
            'CN-BJ' => ['Beijing Shi'],
            'CN-CQ' => ['Chongqing Shi'],
            'CN-FJ' => ['Fujian Sheng'],
            'CN-GD' => ['Guangdong Sheng'],
            'CN-GS' => ['Gansu Sheng'],
            'CN-GX' => ['Guangxi Zhuangzu Zizhiqu'],
            'CN-GZ' => ['Guizhou Sheng'],
            'CN-HA' => ['Henan Sheng'],
            'CN-HB' => ['Hubei Sheng'],
            'CN-HE' => ['Hebei Sheng'],
            'CN-HI' => ['Hainan Sheng'],
            'CN-HK' => ['Xianggang Tebiexingzhengqu',
                             'Hong Kong SAR'],
            'CN-HL' => ['Heilongjiang Sheng'],
            'CN-HN' => ['Hunan Sheng'],
            'CN-JL' => ['Jilin Sheng'],
            'CN-JS' => ['Jiangsu Sheng'],
            'CN-JX' => ['Jiangxi Sheng'],
            'CN-LN' => ['Liaoning Sheng'],
            'CN-MO' => ['Aomen Tebiexingzhengqu',
                             'Macao SAR',
                             'Macau SAR'],
            'CN-NM' => ['Nei Mongol Zizhiqu'],
            'CN-NX' => ['Ningxia Huizu Zizhiqu'],
            'CN-QH' => ['Qinghai Sheng'],
            'CN-SC' => ['Sichuan Sheng'],
            'CN-SD' => ['Shandong Sheng'],
            'CN-SH' => ['Shanghai Shi'],
            'CN-SN' => ['Shaanxi Sheng'],
            'CN-SX' => ['Shanxi Sheng'],
            'CN-TJ' => ['Tianjin Shi'],
            'CN-TW' => ['Taiwan Sheng'],
            'CN-XJ' => ['Xinjiang Uygur Zizhiqu'],
            'CN-XZ' => ['Xizang Zizhiqu'],
            'CN-YN' => ['Yunnan Sheng'],
            'CN-ZJ' => ['Zhejiang Sheng'],
        ],
        'US' => [
            'AL' => ['Alabama'],
            'AK' => ['Alaska'],
            'AS' => ['American Samoa'],
            'AZ' => ['Arizona'],
            'AR' => ['Arkansas'],
            'AE' => [
                'Armed Forces Africa',
                'Armed Forces Europe',
                'Armed Forces Canada',
                'Armed Forces Middle East',
            ],
            'AA' => ['Armed Forces Americas'],
            'AP' => ['Armed Forces Pacific'],
            'CA' => ['California'],
            'CO' => ['Colorado'],
            'CT' => ['Connecticut'],
            'DE' => ['Delaware'],
            'DC' => ['District of Columbia'],
            'FM' => ['Federated States Of Micronesia'],
            'FL' => ['Florida'],
            'GA' => ['Georgia'],
            'GU' => ['Guam'],
            'HI' => ['Hawaii'],
            'ID' => ['Idaho'],
            'IL' => ['Illinois'],
            'IN' => ['Indiana'],
            'IA' => ['Iowa'],
            'KS' => ['Kansas'],
            'KY' => ['Kentucky'],
            'LA' => ['Louisiana'],
            'ME' => ['Maine'],
            'MH' => ['Marshall Islands'],
            'MD' => ['Maryland'],
            'MA' => ['Massachusetts'],
            'MI' => ['Michigan'],
            'MN' => ['Minnesota'],
            'MS' => ['Mississippi'],
            'MO' => ['Missouri'],
            'MT' => ['Montana'],
            'NE' => ['Nebraska'],
            'NV' => ['Nevada'],
            'NH' => ['New Hampshire'],
            'NJ' => ['New Jersey'],
            'NM' => ['New Mexico'],
            'NY' => ['New York'],
            'NC' => ['North Carolina'],
            'ND' => ['North Dakota'],
            'MP' => ['Northern Mariana Islands'],
            'OH' => ['Ohio'],
            'OK' => ['Oklahoma'],
            'OR' => ['Oregon'],
            'PW' => ['Palau'],
            'PA' => ['Pennsylvania'],
            'PR' => ['Puerto Rico'],
            'RI' => ['Rhode Island'],
            'SC' => ['South Carolina'],
            'SD' => ['South Dakota'],
            'TN' => ['Tennessee'],
            'TX' => ['Texas'],
            'UT' => ['Utah'],
            'VT' => ['Vermont'],
            'VI' => ['Virgin Islands'],
            'VA' => ['Virginia'],
            'WA' => ['Washington'],
            'WV' => ['West Virginia'],
            'WI' => ['Wisconsin'],
            'WY' => ['Wyoming'],
        ],
        'TH' => [
            'Amnat Charoen' => ['Amnat Charoen'],
            'Ang Thong' => ['Ang Thong'],
            'Bangkok' => ['Bangkok'],
            'Bueng Kan' => ['Bueng Kan'],
            'Buri Ram' => ['Buri Ram'],
            'Chachoengsao' => ['Chachoengsao'],
            'Chai Nat' => ['Chai Nat'],
            'Chaiyaphum' => ['Chaiyaphum'],
            'Chanthaburi' => ['Chanthaburi'],
            'Chiang Mai' => ['Chiang Mai'],
            'Chiang Rai' => ['Chiang Rai'],
            'Chon Buri' => ['Chon Buri'],
            'Chumphon' => ['Chumphon'],
            'Kalasin' => ['Kalasin'],
            'Kamphaeng Phet' => ['Kamphaeng Phet'],
            'Kanchanaburi' => ['Kanchanaburi'],
            'Khon Kaen' => ['Khon Kaen'],
            'Krabi' => ['Krabi'],
            'Lampang' => ['Lampang'],
            'Lamphun' => ['Lamphun'],
            'Loei' => ['Loei'],
            'Lop Buri' => ['Lop Buri'],
            'Mae Hong Son' => ['Mae Hong Son'],
            'Maha Sarakham' => ['Maha Sarakham'],
            'Mukdahan' => ['Mukdahan'],
            'Nakhon Nayok' => ['Nakhon Nayok'],
            'Nakhon Pathom' => ['Nakhon Pathom'],
            'Nakhon Phanom' => ['Nakhon Phanom'],
            'Nakhon Ratchasima' => ['Nakhon Ratchasima'],
            'Nakhon Sawan' => ['Nakhon Sawan'],
            'Nakhon Si Thammarat' => ['Nakhon Si Thammarat'],
            'Nan' => ['Nan'],
            'Narathiwat' => ['Narathiwat'],
            'Nong Bua Lamphu' => ['Nong Bua Lamphu'],
            'Nong Khai' => ['Nong Khai'],
            'Nonthaburi' => ['Nonthaburi'],
            'Pathum Thani' => ['Pathum Thani'],
            'Pattani' => ['Pattani'],
            'Phang Nga' => ['Phang Nga'],
            'Phatthalung' => ['Phatthalung'],
            'Phatthaya' => ['Phatthaya'],
            'Phayao' => ['Phayao'],
            'Phetchabun' => ['Phetchabun'],
            'Phetchaburi' => ['Phetchaburi'],
            'Phichit' => ['Phichit'],
            'Phitsanulok' => ['Phitsanulok'],
            'Phra Nakhon Si Ayutthaya' => ['Phra Nakhon Si Ayutthaya'],
            'Phrae' => ['Phrae'],
            'Phuket' => ['Phuket'],
            'Prachin Buri' => ['Prachin Buri'],
            'Prachuap Khiri Khan' => ['Prachuap Khiri Khan'],
            'Ranong' => ['Ranong'],
            'Ratchaburi' => ['Ratchaburi'],
            'Rayong' => ['Rayong'],
            'Roi Et' => ['Roi Et'],
            'Sa Kaeo' => ['Sa Kaeo'],
            'Sakon Nakhon' => ['Sakon Nakhon'],
            'Samut Prakan' => ['Samut Prakan'],
            'Samut Sakhon' => ['Samut Sakhon'],
            'Samut Songkhram' => ['Samut Songkhram'],
            'Saraburi' => ['Saraburi'],
            'Satun' => ['Satun'],
            'Si Sa Ket' => ['Si Sa Ket'],
            'Sing Buri' => ['Sing Buri'],
            'Songkhla' => ['Songkhla'],
            'Sukhothai' => ['Sukhothai'],
            'Suphan Buri' => ['Suphan Buri'],
            'Surat Thani' => ['Surat Thani'],
            'Surin' => ['Surin'],
            'Tak' => ['Tak'],
            'Trang' => ['Trang'],
            'Trat' => ['Trat'],
            'Ubon Ratchathani' => ['Ubon Ratchathani'],
            'Udon Thani' => ['Udon Thani'],
            'Uthai Thani' => ['Uthai Thani'],
            'Uttaradit' => ['Uttaradit'],
            'Yala' => ['Yala'],
            'Yasothon' => ['Yasothon'],
        ],
    ];

    /**
     * Returns array of values based on country & state codes, or everything if only country code given
     *
     * @param string $countryCode
     * @param null $stateCode
     *
     * @return bool|array
     */
    public function getValuesFromCodes($countryCode = null, $stateCode = null)
    {
        // We need a countryCode + stateCode and for it to exist in _codes
        if (!$countryCode || !$stateCode || !isset($this->_codes[$countryCode])) {
            return false;
        }

        // If statecode is both given and exists in _codes, return its array value
        if (isset($this->_codes[$countryCode][$stateCode])) {
            return $this->_codes[$countryCode][$stateCode];
        }

        // Nothing found, return false instead
        return false;
    }

    /**
     * Returns code string based on country code and value, or false if not found. Also returns an array if
     *
     * @param null $countryCode
     * @param null $value
     *
     * @return false|string
     */
    public function getCodeFromValue($countryCode = null, $value = null)
    {
        // We need a countryCode + value and for it to exist in _codes
        if (!$countryCode || !$value || !isset($this->_codes[$countryCode])) {
            return false;
        }

        // Loop through and do an in_array search (some state codes have multiple names)
        foreach ($this->_codes[$countryCode] as $stateCode => $stateValues) {
            if (in_array($value, $stateValues)) {
                // As soon as we find one, return the code
                return $stateCode;
            }
        }

        // Nothing found, return false instead
        return false;
    }

    /**
     * Returns all codes or all codes by countryCode. False if countryCode given but non-existant
     *
     * @param null $countryCode
     *
     * @return array|bool
     */
    public function getCodes($countryCode = null)
    {
        if (!$countryCode) {
            return $this->_codes;
        }

        if (isset($this->_codes[$countryCode])) {
            return $this->_codes[$countryCode];
        }

        // Nothing found based on countryCode but it was given, return false instead
        return false;
    }
}
