<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Buckaroo\Magento2\Block\Info\Creditcard
 */
?>
<?php /** @var \Buckaroo\Magento2\Model\Method\BuckarooAdapter $method */ ?>
<?php $method = $block->getMethod(); ?>
<div class="buckaroo_magento2_payment_<?php echo $block->escapeHtml($method->buckarooPaymentMethodCode); ?>">
    <?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
</div>

<div class="buckaroo_magento2_payment_card_<?php echo $block->escapeHtmlAttr($block->getCardCode()); ?>">
    <?php if ($block->getInfo()->getAdditionalInformation()): ?>
        <?php if ($block->getCardType()): ?>
            <!--<br />--><?php echo $block->escapeHtml(__('Selected card: %1', $block->getCardType())); ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
