<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<?php

if ($block->getMethod() instanceof \Magento\Payment\Model\Method\Adapter) {
    $bpePaymentCode = $escaper->escapeHtml($block->getMethod()->getCode());
} else {
    $bpePaymentCode = $escaper->escapeHtml($block->getMethod()->buckarooPaymentMethodCode);
} ?>

<?php
if ($giftCards = $block->getGiftCards()) {
    foreach ($giftCards as $giftCard) { ?>
        <div class="buckaroo_magento2_payment_<?= $escaper->escapeHtml($giftCard['code']); ?>">
            <?= $escaper->escapeHtml($giftCard['label']) ?>
        </div>
        <?php
    }
}
?>

<div class="payment-method buckaroo_magento2_payment_<?= $escaper->escapeHtml($bpePaymentCode) ?>">
    <?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?>
</div>
