<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php foreach ($block->getValues() as $label => $value):?>
    <tr class="totals buckaroo_fee">
        <th class="mark" colspan="<?php /* @escapeNotVerified */ echo $block->getColspan(); ?>" scope="row">
            <span><?php /* @escapeNotVerified */ echo $label; ?></span>
        </th>
        <td class="amount" data-th="<?php echo $block->escapeHtml($label); ?>">
            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value) ?>
        </td>
    </tr>
<?php endforeach; ?>
