<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Buckaroo\Magento2\Block\Info\Creditcard
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    {{pdf_row_separator}}
    <?php if ($block->getCardType()): ?>
        <?php echo $block->escapeHtml(__('Selected card: %1', $block->getCardType())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
