<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Buckaroo\Magento2\Block\Info|\Buckaroo\Magento2\Block\AdminInfo
 */
$specificInfo = $block->getSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
{{pdf_row_separator}}
<?php if ($transactionReference = $block->getPaymentTransactionReference()): ?>
<?= "\xE2\x80\x8B" ?>
{{pdf_row_separator}}
(<?= $block->escapeHtml($transactionReference) ?>)
{{pdf_row_separator}}
<?php endif; ?>
<?php if ($specificInfo): ?>
    <?php foreach ($specificInfo as $label => $value): ?>
        <?= $block->escapeHtml($label) ?>:
        <?= $block->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif; ?>
