<div class="message-system-inner">
    <div class="message-system-short-wrapper">
        <div class="message">
            <?php echo $block->escapeHtml(__("Orders with discount and paid with Klarna can not be partially invoiced. %1 More Information %2",
                "<a href='https://confluence.tig.nl/x/woDWAw' target='_blank'>",
                "</a>")
                ,['a'])?>
        </div>
    </div>
</div>