<?php

/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<!-- Set up a container element for the button -->
<div id="applepay-button-wrapper">
    <apple-pay-button lang="en-US" buttonstyle="<?= $escaper->escapeHtmlAttr($block->getButtonStyle());?>" hidden="false"></apple-pay-button>
</div>
<script type="text/x-magento-init">
{
    "#applepay-button-wrapper": {
        "Buckaroo_Magento2/js/view/adminhtml/applepay": {
            "buttonStyle": "<?= $escaper->escapeJs($block->getButtonStyle()); ?>",
            "buttonStyleElement": "<?= $escaper->escapeJs($block->getButtonStyleElement()); ?>"
        }
    }
}
</script>
