<!-- Gets extra fields if required for this payment method. Returns array of extra fields, or empty array -->
<?php $extraFields = $block->getExtraFields(); ?>

<div class="refund-fields">
    <?php foreach ($extraFields as $name => $field): ?>
        <div class="admin__field" >
            <label for="buckaroo_magento2_<?= $escaper->escapeHtml($field); ?>" class="label normal admin__field-label">
                <?= $escaper->escapeHtml($name); ?>
            </label>
            <input type="text"
                   name="creditmemo[<?= $escaper->escapeHtml($field); ?>]"
                   class="input-text input-text admin__control-text"
                   id="buckaroo_magento2_<?= $escaper->escapeHtml($field); ?>"
                />
        </div>
    <?php endforeach; ?>
</div>
