<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<script type="text/x-magento-init">
{
    "#buckaroo_magento2_credentials_checker_button": {
        "Buckaroo_Magento2/js/view/adminhtml/credentials-checker": {
            "element": "#buckaroo_magento2_credentials_checker_button"
        }
    }
}
</script>

<?= /* @noEscape */ $block->getHtml() ?>
<p class="note"><span id="buckaroo_magento2_credentials_checker_msg"></span></p>
