<?php

/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<!-- Set up a container element for the button -->
<div id="paypal-button-container"></div>
<script type="text/x-magento-init">
{
    "#paypal-button-container": {
        "Buckaroo_Magento2/js/view/adminhtml/paypal": {
            "buttonColor": "<?= $escaper->escapeJs($block->getButtonColor()); ?>",
            "buttonShape": "<?= $escaper->escapeJs($block->getButtonShape()); ?>",
            "buttonColorElement": "<?= $escaper->escapeJs($block->getButtonColorElement()); ?>",
            "buttonShapeElement": "<?= $escaper->escapeJs($block->getButtonShapeElement()); ?>"
        }
    }
}
</script>
