<?php
if ($block->canShowProductButton()): ?>
    <button id="fast-checkout-ideal-btn">Fast Checkout with iDEAL</button>

    <script>
        require(['jquery', 'buckaroo/ideal-fast-checkout/payjs'], function ($, fastCheckout) {
            $('#fast-checkout-ideal-btn').click(function () {
                var productData = {
                    product_id: $('#product_id').val(),
                    qty: $('#qty').val(),
                    paymentData: {
                        method: 'buckaroo_magento2_ideal'
                    }
                };

                fastCheckout.createQuoteAndPlaceOrder(productData);
            });
        });
    </script>
<?php endif; ?>
