<?php

/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

/** @var string $block */

if ($block->canShowButton('Product') && !$block->isIdinVerificationRequired()): ?>

    <div id="fast-checkout-ideal-btn-component" data-bind="scope: 'fastCheckoutIdeal'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
            "#fast-checkout-ideal-btn-component": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "fastCheckoutIdeal": {
                            "component":"buckaroo/ideal-fast-checkout/pay",
                            "template":"Buckaroo_Magento2/catalog/product/view/ideal-fast-checkout",
                                "config": {
                                "page": "product",
                                "buttonVariant": "<?= $escaper->escapeHtmlAttr($block->getButtonVariant()) ?>",
                                "paymentData": {
                                    "method": "buckaroo_magento2_ideal",
                                    "additional_data": {
                                        "issuer": "fastcheckout"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
