<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<?php if ($block->canShowProductIdin()): ?>
<div id="buckaroo_idin_product">
    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Buckaroo_Magento2::images/idin.svg')); ?>"
        alt="Idin Logo"/>
    <span><?= /* @noEscape */ __('The identity check %1 allows you to securely identify yourself. For this, we use a one-time identification using your own bank.', '<br/>'); ?></span>
</div>
<?php endif; ?>

