<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */
?>
<?php if ($block->canShowProductButton() && !$block->isIdinVerificationRequired()): ?>
<div id="paypal-express-button-component" data-bind="scope:'paypalExpress'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <div class="buckaroo-paypal-express"></div>
    <script type="text/x-magento-init">
        {
            "#paypal-express-button-component": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "paypalExpress": {
                            "component":"buckaroo/paypal-express/button",
                            "template":"Buckaroo_Magento2/catalog/product/view/paypal-express",
                            "data":  <?= /* @noEscape */ json_encode($block->getConfig()); ?>
                        }
                    }
                }
            }
        }
    </script>
</div>
<?php endif; ?>