<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Buckaroo\Magento2\Block\Info\Creditcard
 */
?>
<?php /** @var \Buckaroo\Magento2\Model\Method\BuckarooAdapter $method */ ?>
<?php
if ($giftCards = $block->getGiftCards()) {
    foreach ($giftCards as $giftCard) { ?>
        <div class="bk-payment-wrap">
            <div class="bk-img-wrap">
                <img src=" <?php echo $block->escapeHtml($block->getGiftcardLogo($giftCard)) ?>" alt=""/>
            </div>
            <div class="bk-label-wrap">
            <?php echo $block->escapeHtml($giftCard['label']) ?>
            </div>
        </div>
    <?php
    }
}
?>
<?php $method = $block->getMethod(); ?>
<div class="buckaroo_magento2_payment_<?php echo $block->escapeHtml($method->buckarooPaymentMethodCode); ?>">
    <?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
</div>

<div class="buckaroo_magento2_payment_card_<?php echo $block->escapeHtmlAttr($block->getCardCode()); ?>">
    <?php if ($block->getInfo()->getAdditionalInformation()): ?>
        <?php if ($block->getCardType()): ?>
            <div class="bk-payment-wrap">
                <div class="bk-img-wrap">
                    <img src=" <?php echo $block->escapeHtml($block->getCreditcardLogo($block->getCardCode())) ?>" alt=""/>
                </div>
                <div class="bk-label-wrap">
                <?php echo $block->escapeHtml(__('Selected card: %1', $block->getCardType())); ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>

<?php if ($block->getMpiStatus()): ?>
    <div class="buckaroo_magento2_payment_mpi_status">
        <br /><?php echo $block->escapeHtml(__('MPI status:')) ?><br />
        <ul>
            <?php foreach ($block->getMpiStatus() as $key => $value): ?>
                <li><?php echo $block->escapeHtml(__($key . ': %1', $value)); ?> </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
