<?php
/**
 * Buckaroo Magento 2 payment module (https://www.buckaroo.eu/)
 *
 * Copyright (c) Buckaroo B.V.
 * See LICENSE for license details.
 *
 * Support: support@buckaroo.nl
 *
 * @copyright Copyright (c) Buckaroo B.V.
 * @license   MIT
 */

/** @var string $block */
if ($block->canShowCartButton() && !$block->isIdinVerificationRequired()): ?>
    <div id="paypal-express-cart-component">
        <div id="paypal-express-wrapper"></div>
        <div class="buckaroo-paypal-express"></div>
    </div>

    <script type="text/x-magento-init">
    {
        "#paypal-express-wrapper": {
            "Buckaroo_Magento2/js/view/checkout/cart/paypal-express": {
                "config": <?= /* @noEscape */ json_encode($block->getCartConfig()); ?>,
                "context": "cart"
            }
        }
    }
    </script>
<?php endif; ?>
